const STORAGE_KEY='flowday-planner-v3';
const schemaVersion=3;
const defaultData={version:schemaVersion,settings:{workStart:9,workEnd:18,lunchStart:13,lunchEnd:14,buffer:10,blockMax:90},tasks:[
{id:1,title:'Собрать структуру презентации',duration:90,priority:3,deadline:'2026-09-28',category:'Учёба',note:'',scheduledDate:null,scheduledStart:null,locked:false,done:false,createdAt:'2026-09-27T07:00:00Z'},
{id:2,title:'Ответить на важные письма',duration:45,priority:2,deadline:'2026-09-29',category:'Работа',note:'',scheduledDate:'2026-09-27',scheduledStart:'10:00',locked:true,done:false,createdAt:'2026-09-27T07:10:00Z'},
{id:3,title:'Подготовить идеи для проекта',duration:60,priority:3,deadline:'2026-09-30',category:'Работа',note:'',scheduledDate:null,scheduledStart:null,locked:false,done:false,createdAt:'2026-09-27T07:20:00Z'},
{id:4,title:'Записаться на стоматолога',duration:30,priority:1,deadline:'2026-10-02',category:'Личное',note:'',scheduledDate:null,scheduledStart:null,locked:false,done:false,createdAt:'2026-09-27T07:30:00Z'},
{id:5,title:'Изучить 2 главы курса',duration:90,priority:2,deadline:'2026-10-04',category:'Учёба',note:'',scheduledDate:'2026-09-27',scheduledStart:'15:30',locked:true,done:false,createdAt:'2026-09-27T07:40:00Z'}
],focus:{sessions:[],totalMinutes:0}};
let data=load();
let currentDate=startOfDay(new Date());
let currentView='today';
let editingId=null;
let activeFilter='all';
let toastTimer=null;
let focusTimer=null;
let focusLength=Number(data.settings.blockMax)||25;
let focusRemaining=focusLength*60;
let focusRunning=false;

const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
const byId=id=>data.tasks.find(t=>t.id===id);
function clone(v){return JSON.parse(JSON.stringify(v));}
function load(){try{const raw=localStorage.getItem(STORAGE_KEY)||localStorage.getItem('flowday-planner-v2');return normalizeData(raw?JSON.parse(raw):clone(defaultData));}catch{return normalizeData(clone(defaultData));}}
function normalizeData(v){const base=clone(defaultData); if(!v||typeof v!=='object') return base; const settings={...base.settings,...(v.settings||{})}; if(!['system','light','dark'].includes(settings.theme)) settings.theme='system'; const tasks=Array.isArray(v.tasks)?v.tasks.map((t,i)=>({...base.tasks[0],...t,id:Number.isFinite(Number(t.id))?Number(t.id):Date.now()+i,duration:Math.max(15,Number(t.duration)||30),priority:Math.min(3,Math.max(1,Number(t.priority)||2)),locked:Boolean(t.locked),done:Boolean(t.done),scheduledDate:t.scheduledDate||null,scheduledStart:t.scheduledStart||null,deadline:t.deadline||dateKey(new Date())})):clone(base.tasks); const focus={...base.focus,...(v.focus||{})}; if(!Array.isArray(focus.sessions)) focus.sessions=[]; if(!Number.isFinite(Number(focus.totalMinutes))) focus.totalMinutes=0; return {version:schemaVersion,settings,tasks,focus};}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));}
function startOfDay(d){const x=new Date(d);x.setHours(0,0,0,0);return x;}
function dateKey(d){const x=startOfDay(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`;}
function dateFromKey(key){return new Date(`${key}T12:00:00`);}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x;}
function daysBetween(a,b){return Math.round((startOfDay(b)-startOfDay(a))/86400000);}
function shortDate(d){return d.toLocaleDateString('ru-RU',{day:'numeric',month:'short'}).replace('.','');}
function longDate(d){return d.toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'});}
function formatDuration(m){const h=Math.floor(m/60),min=m%60;return h?`${h}ч${min?` ${min}м`:''}`:`${min}м`;}
function hm(m){return `${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;}
function toMinutes(v){const [h,m]=String(v).split(':').map(Number);return h*60+m;}
function priorityLabel(p){return p===3?'Высокий':p===2?'Средний':'Низкий';}
function categoryClass(c){if(c==='Личное')return 'green';if(c==='Дом')return 'yellow';return '';}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function deadlineLabel(t){const d=daysBetween(currentDate,dateFromKey(t.deadline));if(d<0)return `просрочено на ${Math.abs(d)}д`;if(d===0)return 'сегодня';if(d===1)return 'завтра';return `до ${shortDate(dateFromKey(t.deadline))}`;}
function activeScheduled(day){return data.tasks.filter(t=>t.scheduledDate===day&&t.scheduledStart&&!t.done).sort((a,b)=>toMinutes(a.scheduledStart)-toMinutes(b.scheduledStart));}
function allScheduled(day){return data.tasks.filter(t=>t.scheduledDate===day&&t.scheduledStart).sort((a,b)=>toMinutes(a.scheduledStart)-toMinutes(b.scheduledStart));}
function workingMinutes(){return Math.max(0,(data.settings.workEnd-data.settings.workStart)*60-Math.max(0,data.settings.lunchEnd-data.settings.lunchStart)*60);}
function getMonday(d){const x=startOfDay(d),day=x.getDay();x.setDate(x.getDate()+(day===0?-6:1-day));return x;}
function taskScore(t,targetDate){const target=dateFromKey(dateKey(targetDate)),deadline=dateFromKey(t.deadline),days=daysBetween(target,deadline);const urgency=days<0?160:Math.max(0,80-days*11);const durationBonus=Math.max(0,12-t.duration/20);const focusBonus=t.duration>=60?7:0;return t.priority*36+urgency+durationBonus+focusBonus;}
function getFreeWindows(day,occupied){const start=data.settings.workStart*60,end=data.settings.workEnd*60,lunchS=data.settings.lunchStart*60,lunchE=data.settings.lunchEnd*60;const blocks=[...(occupied||[]),{s:lunchS,e:lunchE}].map(x=>({s:Math.max(start,x.s),e:Math.min(end,x.e)})).filter(x=>x.e>x.s).sort((a,b)=>a.s-b.s);const merged=[];for(const b of blocks){const last=merged[merged.length-1];if(last&&b.s<=last.e)last.e=Math.max(last.e,b.e);else merged.push({...b});}const windows=[];let c=start;for(const b of merged){if(b.s>c)windows.push([c,b.s]);c=Math.max(c,b.e);}if(c<end)windows.push([c,end]);return windows;}
function addOccupied(occ,t){if(!t.scheduledDate||!t.scheduledStart)return;const k=t.scheduledDate;(occ[k]??=[]).push({s:toMinutes(t.scheduledStart),e:toMinutes(t.scheduledStart)+t.duration+Number(data.settings.buffer||0)});occ[k].sort((a,b)=>a.s-b.s);}
function findSlot(task,fromDate,occupied){let day=startOfDay(fromDate);const deadline=dateFromKey(task.deadline);for(let i=0;i<370&&day<=deadline;i++,day=addDays(day,1)){const key=dateKey(day),free=getFreeWindows(key,occupied[key]||[]);for(const [ws,we] of free){let start=Math.ceil(ws/15)*15;if(start+task.duration>we)continue;return{date:key,start};}}return null;}
function autoPlanAll(silent=false){data.tasks.forEach(t=>{if(!t.done&&!t.locked){t.scheduledDate=null;t.scheduledStart=null;}});const occ={};data.tasks.filter(t=>!t.done&&t.locked&&t.scheduledDate&&t.scheduledStart).forEach(t=>addOccupied(occ,t));const pending=data.tasks.filter(t=>!t.done&&!t.locked).sort((a,b)=>taskScore(b,currentDate)-taskScore(a,currentDate));let placed=0;for(const t of pending){const slot=findSlot(t,currentDate,occ);if(!slot)continue;t.scheduledDate=slot.date;t.scheduledStart=hm(slot.start);addOccupied(occ,t);placed++;}save();renderAll();if(!silent)showToast(placed?`План готов: ${placed} ${placed===1?'задача распределена':'задач распределено'}.`:'До дедлайнов свободных окон не хватило.');}
function scheduleSingle(id){const t=byId(id);if(!t||t.done)return;t.scheduledDate=null;t.scheduledStart=null;t.locked=false;const occ={};data.tasks.filter(x=>x.id!==id&&x.scheduledDate&&x.scheduledStart).forEach(x=>addOccupied(occ,x));const slot=findSlot(t,currentDate,occ);if(!slot){save();renderAll();showToast('Не найдено свободное окно до дедлайна.');return;}t.scheduledDate=slot.date;t.scheduledStart=hm(slot.start);save();renderAll();showToast(`Задача поставлена: ${shortDate(dateFromKey(slot.date))}, ${t.scheduledStart}.`);}
function unschedule(id){const t=byId(id);if(!t)return;t.scheduledDate=null;t.scheduledStart=null;t.locked=false;save();renderAll();showToast('Слот освобождён.');}
function completeTask(id){const t=byId(id);if(!t)return;t.done=true;t.locked=false;save();closeSheet('taskSheetBackdrop');renderAll();showToast('Задача выполнена.');}
function deleteTask(id){data.tasks=data.tasks.filter(t=>t.id!==id);save();closeSheet('taskSheetBackdrop');renderAll();showToast('Задача удалена.');}
function applyTheme(){const theme=data.settings.theme||'system';document.documentElement.dataset.theme=theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):theme;}
function renderAll(){applyTheme();focusLength=Number(data.settings.blockMax)||25;renderChrome();renderToday();renderCalendar();renderTasksView();renderSettings();populateFocusTasks();updateOfflineBadge();}
function renderChrome(){$('#headerDate').textContent=shortDate(currentDate);$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===currentView));}
function renderToday(){const day=dateKey(currentDate),scheduled=activeScheduled(day),open=data.tasks.filter(t=>!t.done&&!t.scheduledStart),planned=scheduled.reduce((s,t)=>s+t.duration,0),capacity=workingMinutes(),pct=Math.min(100,Math.round(planned/Math.max(1,capacity)*100));const isToday=day===dateKey(new Date());$('#todayEyebrow').textContent=isToday?'СЕГОДНЯ':longDate(currentDate).toUpperCase();$('#todayTitle').textContent=isToday?'Твой день уже собран.':`План на ${shortDate(currentDate)}.`;$('#todayDateText').textContent=shortDate(currentDate);$('#focusValue').textContent=`${pct}%`;$('#focusRingValue').textContent=`${pct}%`;$('#focusLabel').textContent=pct>85?'день почти полный':'дня запланировано';$('#focusProgress').style.width=`${pct}%`;$('#focusRing').style.background=`conic-gradient(#fff ${pct*3.6}deg,rgba(255,255,255,.11) 0deg)`;$('#dayStatusText').textContent=open.length?'ПЛАН ДНЯ':'ДЕНЬ СОБРАН';const next=scheduled.find(t=>toMinutes(t.scheduledStart)>=currentMinutes());$('#insightTitle').textContent=next?`Дальше — ${next.title}`:open.length?'Есть что распределить':'Всё на месте';$('#insightText').textContent=next?`${next.scheduledStart} · ${formatDuration(next.duration)} · ${categoryClass(next.category)==='green'?'личное':next.category.toLowerCase()}`:open.length?`${open.length} задач ждут времени. Нажми «Собрать план».`:'Можно спокойно работать по расписанию.';$('#inboxCount').textContent=open.length;renderTodayAgenda(scheduled);renderTodayInbox(open);}
function currentMinutes(){const d=new Date();return d.getHours()*60+d.getMinutes();}
function renderTodayAgenda(scheduled){const el=$('#todayAgenda');if(!scheduled.length){el.innerHTML='<div class="empty-card"><strong>Пока пусто</strong>Нажми «Собрать план» или поставь задачу вручную.</div>';return;}const now=currentMinutes();el.innerHTML=scheduled.slice(0,5).map((t,i)=>{const start=toMinutes(t.scheduledStart),active=start<=now&&now<start+t.duration&&dateKey(new Date())===t.scheduledDate;return `<button class="agenda-card ${t.locked?'manual':'auto'} ${active?'now-card':''}" style="animation-delay:${i*45}ms" data-edit="${t.id}"><span class="agenda-time">${t.scheduledStart}</span><span class="agenda-main"><span class="agenda-title">${escapeHtml(t.title)}</span><span class="agenda-meta">${formatDuration(t.duration)} · ${escapeHtml(t.category)}${active?' · сейчас':''}</span></span><span class="agenda-arrow">›</span></button>`;}).join('');bindEdit(el);}
function renderTodayInbox(open){const el=$('#todayInbox');if(!open.length){$('#todayInboxBlock').style.display='none';return;}$('#todayInboxBlock').style.display='block';el.innerHTML=open.slice(0,4).sort((a,b)=>taskScore(b,currentDate)-taskScore(a,currentDate)).map((t,i)=>`<div class="inbox-row" style="animation-delay:${i*45}ms"><button class="check-button" data-complete="${t.id}">${t.done?'✓':''}</button><div class="inbox-content"><div class="inbox-title">${escapeHtml(t.title)}</div><div class="inbox-meta">${formatDuration(t.duration)} · ${deadlineLabel(t)} · ${escapeHtml(t.category)}</div></div><button class="small-icon-button" data-edit="${t.id}" aria-label="Изменить">›</button></div>`).join('');if(open.length>4)el.insertAdjacentHTML('beforeend',`<button class="secondary-button wide" id="showMoreTasks">Показать ещё ${open.length-4}</button>`);bindTaskCompletion(el);bindEdit(el);$('#showMoreTasks')?.addEventListener('click',()=>switchView('tasks'));}
function bindTaskCompletion(el){el.querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>completeTask(Number(b.dataset.complete)));}
function bindEdit(el){el.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openTaskSheet(Number(b.dataset.edit)));}
function renderCalendar(){const monday=getMonday(currentDate),end=addDays(monday,6);$('#weekRange').textContent=`${shortDate(monday)} — ${shortDate(end)}`;const strip=$('#weekStrip');strip.innerHTML='';for(let i=0;i<7;i++){const d=addDays(monday,i),key=dateKey(d),tasks=activeScheduled(key),b=document.createElement('button');b.className=`week-day-button ${key===dateKey(currentDate)?'active':''} ${tasks.length?'has-tasks':''}`;b.innerHTML=`<div class="day-name">${d.toLocaleDateString('ru-RU',{weekday:'short'})}</div><div class="day-num">${d.getDate()}</div><div class="day-dot"></div>`;b.onclick=()=>{currentDate=d;renderAll();};strip.appendChild(b);}const scheduled=activeScheduled(dateKey(currentDate)),load=scheduled.reduce((s,t)=>s+t.duration,0),pct=Math.round(load/Math.max(1,workingMinutes())*100);$('#daySummary').innerHTML=`<div><strong>${longDate(currentDate)}</strong><p>${scheduled.length?`${scheduled.length} задач в плане`:'Время пока свободно'}</p></div><div class="summary-number"><strong>${Math.min(100,pct)}%</strong><small>загрузка</small></div>`;renderCalendarAgenda(scheduled);}
function renderCalendarAgenda(scheduled){const el=$('#calendarAgenda');if(!scheduled.length){el.innerHTML='<div class="empty-card"><strong>Нет задач на этот день</strong>Свободное место можно отдать новым задачам.</div>';return;}const start=data.settings.workStart,end=data.settings.workEnd;el.innerHTML='';for(let h=start;h<end;h++){const wrap=document.createElement('div');wrap.className='calendar-hour';const events=scheduled.filter(t=>Math.floor(toMinutes(t.scheduledStart)/60)===h);wrap.innerHTML=`<div class="calendar-hour-label">${String(h).padStart(2,'0')}:00</div><div class="calendar-hour-slot">${events.length?events.map(t=>`<button class="calendar-event ${t.locked?'manual':'auto'}" data-edit="${t.id}"><div class="ce-title">${escapeHtml(t.title)}</div><div class="ce-meta">${t.scheduledStart} · ${formatDuration(t.duration)} · ${t.locked?'ручное время':'авто'}</div></button>`).join(''):' '}</div>`;el.appendChild(wrap);}bindEdit(el);}
function filteredTasks(){const q=$('#taskSearch')?.value.trim().toLowerCase()||'';return data.tasks.filter(t=>{const status=activeFilter==='all'||(activeFilter==='open'&&!t.done)||(activeFilter==='planned'&&!t.done&&!!t.scheduledStart)||(activeFilter==='done'&&t.done);const txt=[t.title,t.category,t.note].join(' ').toLowerCase();return status&&(!q||txt.includes(q));}).sort((a,b)=>{if(a.done!==b.done)return Number(a.done)-Number(b.done);if(!!a.scheduledStart!==!!b.scheduledStart)return Number(!!b.scheduledStart)-Number(!!a.scheduledStart);if(a.deadline!==b.deadline)return a.deadline.localeCompare(b.deadline);return b.priority-a.priority;});}
function renderTasksView(){const tasks=filteredTasks();$('#taskSummary').textContent=`${data.tasks.filter(t=>!t.done).length} открытых · ${data.tasks.filter(t=>t.done).length} готово`;const el=$('#allTaskList');if(!tasks.length){el.innerHTML='<div class="empty-card"><strong>Ничего не найдено</strong>Попробуй другой фильтр или запрос.</div>';return;}el.innerHTML=tasks.map((t,i)=>`<article class="library-card" style="animation-delay:${i*28}ms"><div class="library-top"><button class="check-button ${t.done?'done':''}" data-complete="${t.id}">${t.done?'✓':''}</button><div class="library-main"><div class="library-title ${t.done?'done':''}">${escapeHtml(t.title)}</div><div class="library-meta">${formatDuration(t.duration)} · ${deadlineLabel(t)}${t.scheduledDate&&t.scheduledStart?` · ${shortDate(dateFromKey(t.scheduledDate))} в ${t.scheduledStart}`:''}</div><div class="tag-row"><span class="tag ${t.priority===3?'high':t.priority===2?'medium':''}">${priorityLabel(t.priority)}</span><span class="tag blue">${escapeHtml(t.category)}</span>${t.locked?'<span class="tag">ручное время</span>':''}${t.note?'<span class="tag">заметка</span>':''}</div></div></div><div class="library-actions">${!t.done&&!t.scheduledStart?`<button class="mini-action primary" data-plan="${t.id}">Поставить</button>`:''}${t.scheduledStart&&!t.done?`<button class="mini-action" data-unschedule="${t.id}">Убрать время</button>`:''}<button class="mini-action" data-edit="${t.id}">Изменить</button></div></article>`).join('');bindTaskCompletion(el);bindEdit(el);el.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>scheduleSingle(Number(b.dataset.plan)));el.querySelectorAll('[data-unschedule]').forEach(b=>b.onclick=()=>unschedule(Number(b.dataset.unschedule)));}
function renderSettings(){const s=data.settings;$('#appearanceInput').value=s.theme||'system';$('#workStartInput').value=hm(s.workStart*60);$('#workEndInput').value=hm(s.workEnd*60);$('#lunchStartInput').value=hm(s.lunchStart*60);$('#lunchEndInput').value=hm(s.lunchEnd*60);$('#bufferInput').value=String(s.buffer);$('#blockInput').value=String(s.blockMax);}
function openTaskSheet(id=null){editingId=id;const t=id?byId(id):null;$('#taskSheetKicker').textContent=t?'РЕДАКТИРОВАНИЕ':'НОВАЯ ЗАДАЧА';$('#taskSheetTitle').textContent=t?'Изменить задачу':'Что нужно сделать?';$('#saveTaskBtn').textContent=t?'Сохранить':'Добавить';$('#deleteTaskBtn').hidden=!t;$('#taskTitle').value=t?.title||'';$('#taskDuration').value=String(t?.duration||60);$('#taskPriority').value=String(t?.priority||2);$('#taskDeadline').value=t?.deadline||dateKey(addDays(currentDate,2));$('#taskCategory').value=t?.category||'Учёба';$('#taskNote').value=t?.note||'';const manual=Boolean(t?.scheduledDate&&t?.scheduledStart);$('#manualScheduleToggle').checked=manual;$('#manualScheduleFields').classList.toggle('hidden',!manual);$('#taskScheduleDate').value=t?.scheduledDate||dateKey(currentDate);$('#taskScheduleTime').value=t?.scheduledStart||'';openSheet('taskSheetBackdrop');setTimeout(()=>$('#taskTitle').focus(),250);}
function closeSheet(id){const el=$(`#${id}`);if(!el)return;el.classList.remove('open');el.setAttribute('aria-hidden','true');}
function openSheet(id){const el=$(`#${id}`);if(!el)return;el.classList.add('open');el.setAttribute('aria-hidden','false');}
function closeAllSheets(){$$('.sheet-backdrop.open').forEach(s=>closeSheet(s.id));}
function openFocusSheet(){populateFocusTasks();openSheet('focusSheetBackdrop');}
function populateFocusTasks(){const sel=$('#focusTaskSelect');if(!sel)return;const tasks=data.tasks.filter(t=>!t.done).sort((a,b)=>{if(a.scheduledStart!==b.scheduledStart)return Number(!!b.scheduledStart)-Number(!!a.scheduledStart);return taskScore(b,currentDate)-taskScore(a,currentDate);});const current=sel.value;sel.innerHTML=tasks.length?tasks.map(t=>`<option value="${t.id}">${escapeHtml(t.title)}${t.scheduledStart?` · ${t.scheduledStart}`:''}</option>`).join(''):'<option>Нет открытых задач</option>';if(tasks.some(t=>String(t.id)===current))sel.value=current;}
function updateTimerUI(){const total=Math.max(1,focusLength*60),remain=focusRemaining,pct=(total-remain)/total;$('#timerText').textContent=`${String(Math.floor(remain/60)).padStart(2,'0')}:${String(remain%60).padStart(2,'0')}`;$('#timerMode').textContent=focusRunning?'ФОКУС':'ПАУЗА';$('#timerStart').textContent=focusRunning?'Пауза':'Старт';$('#timerRing').style.background=`conic-gradient(#fff ${pct*360}deg,rgba(255,255,255,.11) 0deg)`;}
function toggleFocus(){if(focusRunning){clearInterval(focusTimer);focusRunning=false;updateTimerUI();return;}focusRunning=true;updateTimerUI();focusTimer=setInterval(()=>{focusRemaining--;if(focusRemaining<=0){clearInterval(focusTimer);focusRunning=false;const id=Number($('#focusTaskSelect').value);const t=byId(id);data.focus.totalMinutes=(data.focus.totalMinutes||0)+focusLength;data.focus.sessions.push({date:dateKey(new Date()),taskId:id,minutes:focusLength});save();showToast(t?`Фокус завершён: ${t.title}`:'Фокус-сессия завершена.');focusRemaining=focusLength*60;renderAll();}updateTimerUI();},1000);}
function resetTimer(){clearInterval(focusTimer);focusRunning=false;focusLength=Number(data.settings.blockMax)||25;focusRemaining=focusLength*60;updateTimerUI();}
function renderInsights(){const monday=getMonday(currentDate);const days=Array.from({length:7},(_,i)=>dateKey(addDays(monday,i)));const completed=data.tasks.filter(t=>t.done).length;const planned=data.tasks.filter(t=>!t.done&&t.scheduledStart).reduce((s,t)=>s+t.duration,0);const sessions=data.focus.sessions||[];$('#insightStats').innerHTML=`<div class="insight-stat"><strong>${completed}</strong><small>готово</small></div><div class="insight-stat"><strong>${formatDuration(planned)}</strong><small>в плане</small></div><div class="insight-stat"><strong>${data.focus.totalMinutes||0}м</strong><small>фокус</small></div>`;const values=days.map(d=>data.tasks.filter(t=>t.scheduledDate===d&&!t.done).reduce((s,t)=>s+t.duration,0));const max=Math.max(60,...values);$('#barChart').innerHTML=values.map((v,i)=>`<div class="chart-bar"><div class="chart-fill" style="height:${Math.max(v?8:2,Math.round(v/max*100))}%"></div><span class="chart-label">${shortDate(dateFromKey(days[i])).split(' ')[0]}</span></div>`).join('');const avg=Math.round(values.reduce((a,b)=>a+b,0)/7);$('#insightRecTitle').textContent=avg>workingMinutes()*.75?'Неделя довольно плотная':'Есть пространство для манёвра';$('#insightRecText').textContent=avg>workingMinutes()*.75?'Оставляй запас и не забивай все окна — так переносы переживаются легче.':`В среднем занято около ${formatDuration(avg)} в день. Можно добавить ещё одну важную задачу.`;openSheet('insightsSheetBackdrop');}
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`flowday-backup-${dateKey(new Date())}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);showToast('Резервная копия подготовлена.');}
function importData(file){const r=new FileReader();r.onload=()=>{try{data=normalizeData(JSON.parse(r.result));save();renderAll();showToast('Данные импортированы.');}catch{showToast('Не удалось прочитать резервную копию.');}};r.readAsText(file);}
function resetDemo(){data=clone(defaultData);save();currentDate=startOfDay(new Date());renderAll();showToast('Демо-данные восстановлены.');}
function updateOfflineBadge(){const online=navigator.onLine;$('#offlineTitle').textContent=online?'Офлайн-режим готов':'Сейчас без интернета';$('#offlineText').textContent=online?'Сайт сохранит основные файлы на устройстве и продолжит работать без сети.':'Все основные функции должны продолжать работать локально.';$('#offlineDot').style.background=online?'var(--green)':'var(--orange)';}
function showToast(msg){clearTimeout(toastTimer);const t=$('#toast');t.textContent=msg;t.classList.add('show');toastTimer=setTimeout(()=>t.classList.remove('show'),2400);}
function switchView(view){if(currentView===view)return;const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;currentView=view;if(!reduce&&document.startViewTransition){document.startViewTransition(()=>{renderChrome();renderAllViews();});}else{renderChrome();renderAllViews();}window.scrollTo({top:0,behavior:reduce?'auto':'smooth'});}
function renderAllViews(){renderToday();renderCalendar();renderTasksView();renderSettings();populateFocusTasks();}
function openQuick(){openSheet('quickSheetBackdrop');}

$('#headerAdd').onclick=()=>openTaskSheet();$('#tabAdd').onclick=openQuick;$('#tasksAddBtn').onclick=()=>openTaskSheet();$('#todayDatePill').onclick=()=>switchView('calendar');$('#calendarToday').onclick=()=>{currentDate=startOfDay(new Date());renderAll();};$('#openCalendarFromToday').onclick=()=>switchView('calendar');$('#planBtn').onclick=()=>autoPlanAll();$('#focusBtn').onclick=openFocusSheet;
$('#headerAction').onclick=()=>{currentDate=startOfDay(new Date());switchView('today');renderAll();};
$$('.tab[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
$('#todayAgenda').addEventListener('click',e=>{const b=e.target.closest('[data-edit]');if(b)openTaskSheet(Number(b.dataset.edit));});
$('#manualScheduleToggle').onchange=e=>$('#manualScheduleFields').classList.toggle('hidden',!e.target.checked);
$('#closeTaskSheet').onclick=()=>closeSheet('taskSheetBackdrop');$('#cancelTask').onclick=()=>closeSheet('taskSheetBackdrop');$('#taskSheetBackdrop').onclick=e=>{if(e.target===e.currentTarget)closeSheet('taskSheetBackdrop')};$('#deleteTaskBtn').onclick=()=>editingId&&deleteTask(editingId);
$('#taskForm').onsubmit=e=>{e.preventDefault();const wasEditing=Boolean(editingId);let task=editingId?byId(editingId):null;const title=$('#taskTitle').value.trim();if(!title){showToast('Введите название задачи.');return;}const manual=$('#manualScheduleToggle').checked;const deadline=$('#taskDeadline').value||dateKey(currentDate);if(!task){task={id:Date.now(),title:'',duration:60,priority:2,deadline,category:'Учёба',note:'',scheduledDate:null,scheduledStart:null,locked:false,done:false,createdAt:new Date().toISOString()};data.tasks.push(task);}Object.assign(task,{title,duration:+$('#taskDuration').value,priority:+$('#taskPriority').value,deadline,category:$('#taskCategory').value,note:$('#taskNote').value.trim()});if(manual){const d=$('#taskScheduleDate').value,t=$('#taskScheduleTime').value;if(!d||!t){showToast('Для ручного времени нужны дата и время.');return;}const start=toMinutes(t),end=start+task.duration;const workS=data.settings.workStart*60,workE=data.settings.workEnd*60,lunchS=data.settings.lunchStart*60,lunchE=data.settings.lunchEnd*60;if(dateFromKey(d)>dateFromKey(deadline)){showToast('Ручной слот позже дедлайна.');return;}if(start<workS||end>workE||(start<lunchE&&end>lunchS)){showToast(`Слот должен быть внутри рабочего дня и вне обеда.`);return;}const conflict=data.tasks.some(x=>x.id!==task.id&&!x.done&&x.scheduledDate===d&&x.scheduledStart&&start<toMinutes(x.scheduledStart)+x.duration&&end>toMinutes(x.scheduledStart));if(conflict){showToast('На это время уже стоит другая задача.');return;}task.scheduledDate=d;task.scheduledStart=t;task.locked=true;}else{task.scheduledDate=null;task.scheduledStart=null;task.locked=false;}save();closeSheet('taskSheetBackdrop');renderAll();showToast(wasEditing?'Изменения сохранены.':'Задача добавлена.');if(!wasEditing&&!manual)scheduleSingle(task.id);};
$('#closeQuickSheet').onclick=()=>closeSheet('quickSheetBackdrop');$('#quickSheetBackdrop').onclick=e=>{if(e.target===e.currentTarget)closeSheet('quickSheetBackdrop')};$('#quickPlan').onclick=()=>{closeSheet('quickSheetBackdrop');autoPlanAll();};$('#quickFocus').onclick=()=>{closeSheet('quickSheetBackdrop');openFocusSheet();};$('#quickNew').onclick=()=>{closeSheet('quickSheetBackdrop');openTaskSheet();};
$('#moreFocus').onclick=openFocusSheet;$('#moreInsights').onclick=renderInsights;$('#morePlanning').onclick=()=>openSheet('planningSheetBackdrop');$('#moreSettings').onclick=()=>openSheet('settingsSheetBackdrop');$('#replanFromSheet').onclick=()=>{closeSheet('planningSheetBackdrop');autoPlanAll();};$('#clearAutoFromSheet').onclick=()=>{data.tasks.forEach(t=>{if(!t.locked&&!t.done){t.scheduledDate=null;t.scheduledStart=null;}});save();closeSheet('planningSheetBackdrop');renderAll();showToast('Автоматические слоты сняты.');};
$('#closeFocusSheet').onclick=()=>{resetTimer();closeSheet('focusSheetBackdrop')};$('#focusSheetBackdrop').onclick=e=>{if(e.target===e.currentTarget){resetTimer();closeSheet('focusSheetBackdrop')}};$('#timerStart').onclick=toggleFocus;$('#timerReset').onclick=resetTimer;$('#focusTaskSelect').onchange=()=>{if(!focusRunning)resetTimer();};
$('#closeInsightsSheet').onclick=()=>closeSheet('insightsSheetBackdrop');$('#insightsSheetBackdrop').onclick=e=>{if(e.target===e.currentTarget)closeSheet('insightsSheetBackdrop')};$('#closePlanningSheet').onclick=()=>closeSheet('planningSheetBackdrop');$('#planningSheetBackdrop').onclick=e=>{if(e.target===e.currentTarget)closeSheet('planningSheetBackdrop')};$('#closeSettingsSheet').onclick=()=>closeSheet('settingsSheetBackdrop');$('#settingsSheetBackdrop').onclick=e=>{if(e.target===e.currentTarget)closeSheet('settingsSheetBackdrop')};
$('#taskSearch').oninput=renderTasksView;$$('#filterRow button').forEach(b=>b.onclick=()=>{$$('#filterRow button').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;renderTasksView();});
$('#settingsForm').onsubmit=e=>{e.preventDefault();const ws=toMinutes($('#workStartInput').value),we=toMinutes($('#workEndInput').value),ls=toMinutes($('#lunchStartInput').value),le=toMinutes($('#lunchEndInput').value);if(!(we>ws)){showToast('Проверь рабочие часы.');return;}if(!(le>ls)||ls<ws||le>we){showToast('Проверь время обеда.');return;}data.settings={...data.settings,workStart:ws/60,workEnd:we/60,lunchStart:ls/60,lunchEnd:le/60,buffer:+$('#bufferInput').value,blockMax:+$('#blockInput').value,theme:$('#appearanceInput').value};save();closeSheet('settingsSheetBackdrop');renderAll();showToast('Настройки сохранены.');};
$('#exportBtn').onclick=exportData;$('#importInput').onchange=e=>{const f=e.target.files?.[0];if(f)importData(f);};$('#resetBtn').onclick=()=>{if(confirm('Вернуть демо-данные и удалить текущие?'))resetDemo();};
matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if((data.settings.theme||'system')==='system')applyTheme();});window.addEventListener('online',updateOfflineBadge);window.addEventListener('offline',updateOfflineBadge);window.addEventListener('scroll',()=>$('.topbar')?.classList.toggle('scrolled',scrollY>5),{passive:true});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAllSheets();if(e.key==='n'&&(e.metaKey||e.ctrlKey)){e.preventDefault();openTaskSheet();}});

// Register the service worker without requiring network after installation.
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
renderAll();updateTimerUI();
