import fs from 'node:fs';
import assert from 'node:assert/strict';
const app = fs.readFileSync(new URL('../app.js', import.meta.url), 'utf8');
const html = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const server = fs.readFileSync(new URL('../sync-service/server.mjs', import.meta.url), 'utf8');
const css = fs.readFileSync(new URL('../style.css', import.meta.url), 'utf8');
assert.match(app, /const APP_VERSION = '12\.1\.0';/);
assert(app.includes("params.set('force', '1')"));
assert(app.includes("params = new URLSearchParams({ group, range: range === 'current' ? 'current' : 'all' })"));
assert(app.includes("const changes = applyUniversitySchedule(next, { partial: responseRange === 'current' })"));
assert(server.includes("const range = String(req.query.range || 'all')"));
assert(server.includes('collectAllAvailableWeeks'));
assert(server.includes('[REA_FULL_RANGE]'));
assert(server.includes("serviceWorkers: 'allow'"));
assert(html.includes('app.js?v=12.1.0'));
assert(html.includes('style.css?v=12.1.0'));
assert(html.includes('config.js?v=12.1.0'));
assert(css.includes('.compact-action.is-error'));
console.log('Current refresh/search compatibility tests passed.');
