import fs from 'node:fs';
import assert from 'node:assert/strict';
const root = new URL('..', import.meta.url);
const server = fs.readFileSync(new URL('./sync-service/server.mjs', root), 'utf8');
const app = fs.readFileSync(new URL('./app.js', root), 'utf8');
const html = fs.readFileSync(new URL('./index.html', root), 'utf8');
const sw = fs.readFileSync(new URL('./sw.js', root), 'utf8');
assert.match(server, /async function ensureWeekPickerOpen/);
assert.match(server, /async function discoverWeekControls/);
assert.match(server, /async function clickWeekControl/);
assert.match(server, /async function collectAllAvailableWeeks/);
assert.match(server, /\[REA_FULL_RANGE\]/);
assert.match(server, /range === 'all'/);
assert.match(server, /weeksScanned/);
assert.match(server, /coverageStart/);
assert.match(server, /coverageEnd/);
assert.match(server, /cacheKey = `\$\{key\}\|\$\{range\}`/);
assert.match(app, /range: range === 'current' \? 'current' : 'all'/);
assert.match(app, /partial: responseRange === 'current'/);
assert.match(app, /lastFullSyncAt/);
assert.match(app, /getUniversityAutoSyncRange/);
assert.match(html, /apple-touch-icon-v18\.png/);
assert.match(sw, /tavrimo-v12\.1\.0-rea-full-range-1/);
console.log('Full-range sync 12.1.0 tests passed.');
