import fs from 'node:fs';
import assert from 'node:assert/strict';
const app = fs.readFileSync(new URL('../app.js', import.meta.url), 'utf8');
const html = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const server = fs.readFileSync(new URL('../sync-service/server.mjs', import.meta.url), 'utf8');
const css = fs.readFileSync(new URL('../style.css', import.meta.url), 'utf8');
assert(app.includes("const APP_VERSION = '12.0.6';"));
assert(app.includes("params.set('force', '1')"));
assert(app.includes("$('#homeSyncBtn')?.addEventListener('click', runManualUniversityRefresh)"));
assert(app.includes("$('#syncUniversityNowBtn')?.addEventListener('click', runManualUniversityRefresh)"));
assert(app.includes('Повторить'));
assert(server.includes("serviceWorkers: 'allow'"));
assert(server.includes('selectGroupTab'));
assert(server.includes('selectGroupOption'));
assert(server.includes(".material-icons"));
assert(server.includes("const force = /^(1|true|yes)$/i.test(String(req.query.force || ''));"));
assert(server.includes("X-Tavrimo-Refresh-Mode"));
assert(html.includes('app.js?v=12.0.6'));
assert(html.includes('style.css?v=12.0.6'));
assert(html.includes('config.js?v=12.0.6'));
assert(css.includes('.compact-action.is-error'));
console.log('Tavrimo 12.0.6 refresh/search release tests passed.');
