import fs from 'node:fs';
import assert from 'node:assert/strict';
const root = new URL('..', import.meta.url);
const app = fs.readFileSync(new URL('./app.js', root), 'utf8');
const html = fs.readFileSync(new URL('./index.html', root), 'utf8');
const server = fs.readFileSync(new URL('./sync-service/server.mjs', root), 'utf8');
const sw = fs.readFileSync(new URL('./sw.js', root), 'utf8');
assert.match(app, /#homeSyncBtn/);
assert.match(app, /#syncUniversityNowBtn/);
assert.match(app, /force:\s*true,\s*silent:\s*false/);
assert.match(app, /navigator\.onLine is only a hint/i);
assert.match(html, /app\.js\?v=12\.0\.5/);
assert.match(html, /style\.css\?v=12\.0\.5/);
assert.match(html, /config\.js\?v=12\.0\.5/);
assert.match(server, /serviceWorkers:\s*'allow'/);
assert.match(server, /async function clickPortalRefresh/);
assert.match(server, /async function clickPortalSearch/);
assert.match(server, /async function searchForGroup/);
assert.match(sw, /tavrimo-v12\.0\.5-refresh-sync-fixed-2/);
console.log('Tavrimo 12.0.5 refresh + REA sync release checks passed.');
