import fs from 'node:fs';
import assert from 'node:assert/strict';
const root = new URL('..', import.meta.url);
const version = fs.readFileSync(new URL('./VERSION', root), 'utf8').trim();
assert.equal(version, '12.0.5');
const app = fs.readFileSync(new URL('./app.js', root), 'utf8');
assert.match(app, /universitySyncController/);
assert.match(app, /manual refresh must always do something/i);
assert.match(app, /button\.textContent = universitySyncInFlight/);
const config = fs.readFileSync(new URL('./config.js', root), 'utf8');
assert.ok(config.includes('\\.github\\.io'));
assert.match(config, /tavrimo-rea-sync\.onrender\.com\/api\/rea\/schedule/);
const server = fs.readFileSync(new URL('./sync-service/server.mjs', root), 'utf8');
assert.match(server, /function parseScheduleText\(/);
assert.match(server, /08:30/);
assert.match(server, /22:00/);
const sw = fs.readFileSync(new URL('./sw.js', root), 'utf8');
assert.match(sw, /tavrimo-v12\.0\.5-refresh-sync-fixed-2/);
console.log('Tavrimo 12.0.5 release checks passed.');
